language: php
php:
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1
sudo: required
dist: trusty
addons:
  hosts:
  - riak-test
before_script:
- phpenv config-rm xdebug.ini
- composer self-update
- composer install --prefer-source
- sudo ./tools/travis-ci/riak-install
- sudo ./tools/devrel/riak-cluster-config "$(which riak-admin)" 8098 false false
- riak version
notifications:
  slack:
    secure: ZtgcjTxhTxrzWW6MIHLRtucW/BMm42RKS3nGRtSfgER9rx7oJ0Y9gOYkh1FM0GsM7Z11Q/iDhWs/8WTccAV0PrMZ6KHaq54wGmfYyqwPM4YreUwQ87PnOW4wZbl0TJTeWutasEwZvnVJ8VEyyQcS2PHt0zlsENn0XWvobvaZ+FM=
script: "./vendor/bin/phpunit --coverage-text"
matrix:
  allow_failures:
  - php: 7.1
